// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZwBLkfJiA8aWoHzPfUWHFTF5jY7O9_nw',
    appId: '1:984666533062:android:c351377c7a9809dd9f7bc7',
    messagingSenderId: '984666533062',
    projectId: 'e-commerce-aaf11',
    storageBucket: 'e-commerce-aaf11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYcO4A3-z1a36YowGiijTylb2QneDAwIM',
    appId: '1:984666533062:ios:77fd0ad3c5affbf29f7bc7',
    messagingSenderId: '984666533062',
    projectId: 'e-commerce-aaf11',
    storageBucket: 'e-commerce-aaf11.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNTqLk7bOJGSOtjwpnFZt0AmqNvAyDPug',
    appId: '1:984666533062:web:471b2fc69a878fc19f7bc7',
    messagingSenderId: '984666533062',
    projectId: 'e-commerce-aaf11',
    authDomain: 'e-commerce-aaf11.firebaseapp.com',
    storageBucket: 'e-commerce-aaf11.firebasestorage.app',
  );

}